title: Ariel Richmond-Parks # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-Driven Marketer • Google Certified Data Analyst • Google Certified Project Manager
  <br><br>
 <a href="https://arielrp01.github.io/aboutme">About Me</a>
  <br><br>
  <a href="https://www.linkedin.com/in/arielrichmondparks/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
