title: Ariel Richmond-Parks # your name (or website title) here
logo: "..." # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-Driven Marketer • Google Certified Data Analyst • Google Certified Project Manager
  <br><br>
  Actively seeking returnships/full-time opportunities
  <br><br>
  <a href="https://www.linkedin.com/in/arielrichmondparks/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
